---
application:
  name: "mr-shinchan-music"
  project: "Mr.Shinchan_Music"
  organization: "QoveryCommunity"
routers:
- name: "main-mr-shinchan-music"
  routes:
  - application_name: "mr-shinchan-music"
    paths:
    - "/*"
