---
application:
  name: "mr-shinchan-music"
  project: "ShinchanHelper"
  organization: "QoveryCommunity"
  cpu: "2"
  ram: "4GB"
  storage:
  - name: "Shinchan-Helper"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/Shinchan-Helper"
routers:
- name: "main-mr-shinchan-music"
  routes:
  - application_name: "mr-shinchan-music"
    paths:
    - "/*"
