---
application:
  name: "mr-shinchan-music"
  project: "Shinchan-Helper"
  organization: "QoveryCommunity"
  storage:
  - name: "shinchanhelper"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/shinchanhelper"
routers:
- name: "main-mr-shinchan-music"
  routes:
  - application_name: "mr-shinchan-music"
    paths:
    - "/*"
